[tools]
fzf = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
neovim = "latest"
lazygit = "latest"
claude = "latest"
aws = "latest"
bun = "latest"
gh = "latest"
php = "latest"
jq = "latest"
gemini = "latest"
uv = "latest"
